import { ImageOperation } from './types';

export const IMAGE_OPERATIONS: Record<string, ImageOperation> = {
  // ------------------------------------------------------------
  // CATEGORY A — PRODUCT PHOTO CLEANUP (1-15)
  // ------------------------------------------------------------
  CLEAN_STUDIO: {
    id: 'CLEAN_STUDIO',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Clean Studio Photo',
    description: 'Create a clean neutral studio product photograph with balanced soft lighting.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Clean professional studio product photograph of {SUBJECT}. Positioned centrally on a smooth neutral seamless studio surface. Soft diffused commercial studio lighting with gentle natural contact shadow beneath the product. High commercial clarity, pure product focus.',
    preservationRules: ['Preserve exact product shape, colors, material texture, and craftsmanship details.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
    recommendedUse: 'General online selling & marketplace listings',
    badge: 'Popular',
  },
  WHITE_BACKGROUND: {
    id: 'WHITE_BACKGROUND',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Pure White Background',
    description: 'Place the product against a crisp, pure white commercial studio background.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Isolated commercial catalog photograph of {SUBJECT} on a 100% pure solid white background (#FFFFFF). Soft natural drop shadow directly beneath product base to anchor it realistically. Crisp edges and accurate product color preservation.',
    preservationRules: ['Lock product geometry, texture, and natural colors without alteration.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
    recommendedUse: 'Amazon & Flipkart primary product compliance',
    badge: 'Marketplace Standard',
  },
  LIGHT_BACKGROUND: {
    id: 'LIGHT_BACKGROUND',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Bright Neutral Backdrop',
    description: 'Create a bright, tasteful warm-grey or soft off-white commercial backdrop.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Commercial photograph of {SUBJECT} placed against a warm off-white and pale cream textured matte backdrop. Gentle daylight illumination with soft gradual falloff.',
    preservationRules: ['Preserve authentic craft color gradients and physical dimensions.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  NATURAL_CRAFT: {
    id: 'NATURAL_CRAFT',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Natural Craft Setting',
    description: 'Present the product on a natural earthy surface such as handloom linen or stone.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Artisan product photograph of {SUBJECT} displayed upon an unbleached organic hand-woven cotton canvas surface. Gentle directional sunlight highlighting artisanal textures and authentic materials.',
    preservationRules: ['Preserve all handmade motifs, hand-painted details, and woven textures.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
    badge: 'Artisan Favorite',
  },
  WOODEN_SURFACE: {
    id: 'WOODEN_SURFACE',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Rustic Wood Surface',
    description: 'Present the product on a rich, restrained natural wood surface with warm tones.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'E-commerce showcase of {SUBJECT} resting upon a rich weathered natural teakwood tabletop. Soft golden-hour window light casting subtle warm highlights on the product contours.',
    preservationRules: ['Retain exact product geometry and handmade imperfections.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  FESTIVE_CULTURAL: {
    id: 'FESTIVE_CULTURAL',
    category: 'photo_cleanup',
    humanCategory: 'Seasonal',
    label: 'Festive Cultural Setting',
    description: 'Create a tasteful cultural celebration presentation with marigold or brass accents.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['festivalOrOccasion'],
    promptTemplate: 'Refined cultural celebration showcase of {SUBJECT}. Tastefully complemented by out-of-focus brass accents, fresh marigold flower petals, and soft warm diya luminescence in the background. The craft product remains the clear hero.',
    preservationRules: ['Keep product completely unaltered; decorations stay strictly in peripheral background.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
    badge: 'Festive',
  },
  MINIMAL_LIFESTYLE: {
    id: 'MINIMAL_LIFESTYLE',
    category: 'photo_cleanup',
    humanCategory: 'Lifestyle',
    label: 'Minimal Lifestyle Setting',
    description: 'Create a clean, uncluttered contemporary lifestyle context with the product dominant.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Modern minimalist interior vignette featuring {SUBJECT} as the primary focal point on a sleek stone console table. Soft diffused architectural lighting, neutral Japandi tones, clean negative space.',
    preservationRules: ['Do not modify product proportions or surface finish.'],
    aspectRatioRules: '4:5',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
  },
  PREMIUM_STUDIO: {
    id: 'PREMIUM_STUDIO',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Premium Luxury Studio',
    description: 'Create an upscale editorial studio shot with dramatic yet natural lighting.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'High-end editorial studio photograph of {SUBJECT}. Matte charcoal and deep olive gradient backdrop with sculptured rim lighting accentuating product silhouette. Premium boutique aesthetic.',
    preservationRules: ['Zero distortion to product craftwork and color accuracy.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
  },
  SOFT_DAYLIGHT: {
    id: 'SOFT_DAYLIGHT',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Soft Morning Daylight',
    description: 'Illuminate with gentle, authentic morning window daylight for genuine natural colors.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Natural daylight product capture of {SUBJECT}. Placed beside a large sunlit window with soft sheer curtain diffusion. Warm natural shadows, authentic color representation, zero harsh reflections.',
    preservationRules: ['Preserve authentic color temperature of handmade raw materials.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  SHADOW_REFINEMENT: {
    id: 'SHADOW_REFINEMENT',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Realistic Shadow Fix',
    description: 'Create a realistic, subtle contact shadow beneath the product to ground it naturally.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Studio refinement of {SUBJECT}. Replaced harsh, floating or unnatural shadows with a delicate, realistic soft contact shadow grounding the product onto a clean surface.',
    preservationRules: ['Keep product pixel boundary intact; only refine underside shadow gradients.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  REFLECTION_CONTROL: {
    id: 'REFLECTION_CONTROL',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Glare & Reflection Control',
    description: 'Reduce distracting specular flare while preserving true metallic or glazed sheen.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Glare-reduced product photograph of {SUBJECT}. Controlled harsh flashlight reflections and lens flare while faithfully maintaining natural luster, clay glaze, or metallic brass sheen.',
    preservationRules: ['Preserve underlying material texture and true colors.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  BACKGROUND_CLEANUP: {
    id: 'BACKGROUND_CLEANUP',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Remove Clutter',
    description: 'Remove distracting everyday clutter around the product and isolate it cleanly.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Product cleanup photograph of {SUBJECT}. Removed all background domestic clutter, wires, boxes, and stray objects, replacing with a clean serene neutral e-commerce studio background.',
    preservationRules: ['Product stays 100% untouched and centered; only surrounding clutter removed.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
    badge: 'Essential',
  },
  FLOOR_CLEANUP: {
    id: 'FLOOR_CLEANUP',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Replace Floor Surface',
    description: 'Replace unsuitable tiles or ground surfaces with a refined wooden or stone pedestal.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Surface replacement for {SUBJECT}. Lifted off rough floor and positioned elegantly on a smooth polished sandstone or warm oak surface with natural ambient lighting.',
    preservationRules: ['Retain product base silhouette precisely.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  WALL_CLEANUP: {
    id: 'WALL_CLEANUP',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Replace Wall Backdrop',
    description: 'Replace stained, peeling or distracting walls with a pristine architectural studio wall.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Backdrop overhaul for {SUBJECT}. Replaced distracting background wall with a subtle textured lime-wash architectural wall in soft sand and warm grey.',
    preservationRules: ['Do not change product lighting direction or core craft features.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  COMPOSITION_CENTER: {
    id: 'COMPOSITION_CENTER',
    category: 'photo_cleanup',
    humanCategory: 'Product Photo',
    label: 'Re-center & Balance',
    description: 'Re-align and center the product with balanced margins on all sides.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Balanced catalog crop and composition of {SUBJECT}. Product centered with 15% breathing room on all sides, upright orientation, symmetrical eye-level perspective.',
    preservationRules: ['Preserve true product aspect ratio and shape without stretching.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },

  // ------------------------------------------------------------
  // CATEGORY B — PRODUCT IMAGE QUALITY (16-25)
  // ------------------------------------------------------------
  LIGHTING_IMPROVEMENT: {
    id: 'LIGHTING_IMPROVEMENT',
    category: 'image_quality',
    humanCategory: 'Product Photo',
    label: 'Enhance Exposure & Light',
    description: 'Naturally lift dark shadows and balance highlights without artificial overexposure.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Expert lighting enhancement of {SUBJECT}. Lifted underexposed shadows to reveal intricate craftsmanship, balanced highlights to eliminate blowout, three-point studio lighting balance.',
    preservationRules: ['Maintain authentic craft material colors and natural shades.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  COLOR_BALANCE: {
    id: 'COLOR_BALANCE',
    category: 'image_quality',
    humanCategory: 'Product Photo',
    label: 'True Color Balance',
    description: 'Neutralize yellow or blue camera tint while preserving true natural dye colors.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Color-corrected product photograph of {SUBJECT}. Neutral white balance, accurate natural pigment calibration, elimination of yellow fluorescent casts while preserving organic vegetable dye tones.',
    preservationRules: ['Match true textile, terracotta or brass colors accurately.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  SHARPNESS_IMPROVEMENT: {
    id: 'SHARPNESS_IMPROVEMENT',
    category: 'image_quality',
    humanCategory: 'Product Photo',
    label: 'Clarity & Sharpness',
    description: 'Enhance apparent focal clarity and edge sharpness without introducing artificial noise.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'High-clarity commercial product image of {SUBJECT}. Crisp edge definition, micro-contrast enhancement on intricate carving or embroidery, elimination of camera motion blur.',
    preservationRules: ['Do not hallucinate non-existent details; enhance real optical sharpness.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  CONTRAST_BALANCE: {
    id: 'CONTRAST_BALANCE',
    category: 'image_quality',
    humanCategory: 'Product Photo',
    label: 'Dynamic Contrast Balance',
    description: 'Improve depth and dynamic range while keeping delicate textures fully visible.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Balanced dynamic contrast enhancement for {SUBJECT}. Deepened rich shadows while retaining weave and fiber texture, clean highlights, professional tonal curve.',
    preservationRules: ['No clipping in dark regions or blown highlights.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  DETAIL_PRESERVATION: {
    id: 'DETAIL_PRESERVATION',
    category: 'image_quality',
    humanCategory: 'Product Photo',
    label: 'Preserve Craft Details',
    description: 'Highlight fine handwork, filigree, embroidery stitches, or brushwork.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Artisan detail-focused commercial photograph of {SUBJECT}. Raking light highlighting delicate handloom threads, hand-chiseled wood grains, or hand-painted strokes with extreme fidelity.',
    preservationRules: ['All physical handcraft details must remain untouched and celebrated.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
  },
  PROFESSIONAL_CROP: {
    id: 'PROFESSIONAL_CROP',
    category: 'image_quality',
    humanCategory: 'Product Photo',
    label: 'Professional Commercial Crop',
    description: 'Crop to e-commerce industry standard with optimal product prominence.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Professional e-commerce crop of {SUBJECT}. Product occupies 80-85% of total frame area, upright level horizon, compliant with ONDC and Amazon marketplace standards.',
    preservationRules: ['Do not cut off any portion of the product.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  SQUARE_PRODUCT_SHOT: {
    id: 'SQUARE_PRODUCT_SHOT',
    category: 'image_quality',
    humanCategory: 'Product Photo',
    label: 'Square Product Shot (1:1)',
    description: 'Square frame tailored for e-commerce listings, marketplace grids, and feed posts.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Standard 1:1 square e-commerce catalog image of {SUBJECT} centered perfectly on a clean neutral background with balanced margin.',
    preservationRules: ['Keep product aspect ratio true inside square canvas.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  PORTRAIT_PRODUCT_SHOT: {
    id: 'PORTRAIT_PRODUCT_SHOT',
    category: 'image_quality',
    humanCategory: 'Product Photo',
    label: 'Portrait Product Shot (4:5)',
    description: 'Vertical 4:5 orientation ideal for apparel, saris, tall crafts, and mobile screens.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Vertical 4:5 portrait commercial composition of {SUBJECT}. Full height display with generous top and bottom breathing space, professional lighting gradient.',
    preservationRules: ['Ensure full vertical silhouette of product is displayed.'],
    aspectRatioRules: '4:5',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  LANDSCAPE_PRODUCT_SHOT: {
    id: 'LANDSCAPE_PRODUCT_SHOT',
    category: 'image_quality',
    humanCategory: 'Product Photo',
    label: 'Landscape Showcase (16:9)',
    description: 'Horizontal banner composition suitable for website headers and desktop banners.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Cinematic 16:9 landscape e-commerce hero shot of {SUBJECT}. Positioned with rule-of-thirds composition, elegant background depth of field, generous negative space on one side.',
    preservationRules: ['Maintain product fidelity in focal zone.'],
    aspectRatioRules: '16:9',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  MARKETPLACE_PRIMARY_IMAGE: {
    id: 'MARKETPLACE_PRIMARY_IMAGE',
    category: 'image_quality',
    humanCategory: 'Product Photo',
    label: 'Amazon & ONDC Ready (Primary)',
    description: 'Full marketplace compliance: pure solid white background, 85% frame coverage, zero props.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Official marketplace primary listing photo for {SUBJECT}. 100% pure solid white background (#FFFFFF), centered framing occupying 85% of frame, subtle grounding shadow, absolutely zero text, logos, or watermarks.',
    preservationRules: ['Strict product isolation. Zero background elements, no borders, no text.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
    badge: '1-Click Marketplace',
  },

  // ------------------------------------------------------------
  // CATEGORY C — PRODUCT CONTEXT / LIFESTYLE (26-35)
  // ------------------------------------------------------------
  HOME_DECOR_CONTEXT: {
    id: 'HOME_DECOR_CONTEXT',
    category: 'lifestyle_context',
    humanCategory: 'Lifestyle',
    label: 'Living Room Setting',
    description: 'Place product in a tastefully styled living room or home decor environment.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Warm, believable modern Indian living room interior featuring {SUBJECT} on a polished wooden credenza. Soft natural sunlight through sheer blinds, tasteful indoor planter in background, blurred cozy ambient backdrop.',
    preservationRules: ['Product remains the clear focal hero; background is subtly defocused.'],
    aspectRatioRules: '4:5',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
    badge: 'Lifestyle',
  },
  KITCHEN_CONTEXT: {
    id: 'KITCHEN_CONTEXT',
    category: 'lifestyle_context',
    humanCategory: 'Lifestyle',
    label: 'Kitchen & Dining Setting',
    description: 'Place pottery, cookware or food-grade crafts in a realistic kitchen or dining setting.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Warm kitchen counter setting displaying {SUBJECT}. Clean granite or wooden countertop, soft morning light, subtle culinary background elements softly blurred.',
    preservationRules: ['Keep product completely in focus and true to size.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
  },
  FESTIVAL_CONTEXT: {
    id: 'FESTIVAL_CONTEXT',
    category: 'lifestyle_context',
    humanCategory: 'Seasonal',
    label: 'Festival Celebration Ambience',
    description: 'Set in a festive Indian home celebration with subtle lights and marigold accents.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['festivalOrOccasion'],
    promptTemplate: 'Festive celebration ambience for {SUBJECT}. Soft glowing fairy lights and golden brass diya reflections in the warm evening bokeh background, authentic festive warmth.',
    preservationRules: ['Never cover product with festive items; decorations remain strictly background framing.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
  },
  GIFTING_CONTEXT: {
    id: 'GIFTING_CONTEXT',
    category: 'lifestyle_context',
    humanCategory: 'Marketing',
    label: 'Gifting Presentation',
    description: 'Present product accompanied by tasteful eco-friendly gift wrap and twine.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Artisanal gift presentation showcasing {SUBJECT}. Arranged beside unrolled brown kraft paper, jute twine, and a subtle handmade blank gift tag. Warm thoughtful boutique mood.',
    preservationRules: ['Product is unwrapped and completely visible as the centerpiece.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
  },
  HANDMADE_CRAFT_CONTEXT: {
    id: 'HANDMADE_CRAFT_CONTEXT',
    category: 'lifestyle_context',
    humanCategory: 'Lifestyle',
    label: 'Artisan Workshop Heritage',
    description: 'Place in a quiet, authentic craft studio setting showing natural raw materials.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Artisan heritage workshop vignette of {SUBJECT}. Placed on a traditional craftsman worktable with natural raw fiber skeins, wooden blocks, or clay pottery tools resting naturally in soft background focus.',
    preservationRules: ['Product must appear finished and perfect; craft tools stay secondary.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
    badge: 'Artisan Heritage',
  },
  DESK_CONTEXT: {
    id: 'DESK_CONTEXT',
    category: 'lifestyle_context',
    humanCategory: 'Lifestyle',
    label: 'Workplace & Desk Setting',
    description: 'Showcase on a stylish work desk or study table with tasteful stationery.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Contemporary workspace desk setting with {SUBJECT} placed prominently. Clean oak tabletop, leather notebook, ceramic coffee mug in soft bokeh background.',
    preservationRules: ['Keep product dominant and sharp.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
  },
  TABLETOP_CONTEXT: {
    id: 'TABLETOP_CONTEXT',
    category: 'lifestyle_context',
    humanCategory: 'Lifestyle',
    label: 'Elegant Tabletop Display',
    description: 'Display on an elegant dining or display tabletop with natural textiles.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Refined tabletop showcase featuring {SUBJECT}. Placed on an earthy textured handloom runner over light wood, bathed in soft afternoon sidelight.',
    preservationRules: ['Maintain product surface reflections and colors.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
  },
  OUTDOOR_CONTEXT: {
    id: 'OUTDOOR_CONTEXT',
    category: 'lifestyle_context',
    humanCategory: 'Lifestyle',
    label: 'Natural Outdoor Sunlight',
    description: 'Place in a serene outdoor setting with natural foliage and golden sunlight.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Serene outdoor garden or patio setting with {SUBJECT} placed on a natural stone slab. Dappled natural sunlight filtering through leaves, lush greenery in background bokeh.',
    preservationRules: ['Protect product from unrealistic outdoor elements or weather.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
  },
  RURAL_CRAFT_CONTEXT: {
    id: 'RURAL_CRAFT_CONTEXT',
    category: 'lifestyle_context',
    humanCategory: 'Lifestyle',
    label: 'Authentic Rural Courtyard',
    description: 'A subtle, respectful rural craft courtyard with traditional sun-baked mud plaster.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Respectful authentic heritage setting featuring {SUBJECT}. Displayed in an Indian rural artisan courtyard with natural sun-baked clay textures, terracotta tiles, and clean morning daylight. Dignified, authentic, non-stereotypical.',
    preservationRules: ['Maintain proud artisanal presentation without cliché stereotypes.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
  },
  PREMIUM_BOUTIQUE_CONTEXT: {
    id: 'PREMIUM_BOUTIQUE_CONTEXT',
    category: 'lifestyle_context',
    humanCategory: 'Branding',
    label: 'Luxury Boutique Gallery',
    description: 'Display inside an upscale craft boutique gallery with museum spotlighting.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Exclusive design gallery boutique display of {SUBJECT}. Placed on a museum-quality matte white or fluted stone plinth. Focused soft spotlighting from above, architectural gallery space.',
    preservationRules: ['Elevate perceived value while maintaining exact craft reality.'],
    aspectRatioRules: '4:5',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
    badge: 'Luxury',
  },

  // ------------------------------------------------------------
  // CATEGORY D — MARKETING ASSETS (36-45)
  // ------------------------------------------------------------
  INSTAGRAM_POST: {
    id: 'INSTAGRAM_POST',
    category: 'marketing_assets',
    humanCategory: 'Social Media',
    label: 'Instagram Feed Post (4:5 / 1:1)',
    description: 'Square or 4:5 vertical aesthetic social composition optimized for engagement.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['marketingText', 'brandContext'],
    promptTemplate: 'Aesthetic high-engagement Instagram post featuring {SUBJECT}. Eye-catching composition with balanced negative space for social layout. Warm earthy palette, contemporary styling.',
    preservationRules: ['Product remains the unmissable center; leave space for optional text overlay.'],
    aspectRatioRules: '4:5',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
    badge: 'Social Media',
  },
  INSTAGRAM_STORY: {
    id: 'INSTAGRAM_STORY',
    category: 'marketing_assets',
    humanCategory: 'Social Media',
    label: 'Instagram & WhatsApp Story (9:16)',
    description: 'Full-screen 9:16 vertical story graphic with product in lower-center and header space.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['marketingText', 'brandContext'],
    promptTemplate: 'Vertical 9:16 full-screen mobile story visual centered on {SUBJECT}. Clean vertical breathing room at top and bottom for mobile UI overlays. Crisp lighting and immersive aesthetic.',
    preservationRules: ['Product positioned in middle-lower third safe zone.'],
    aspectRatioRules: '9:16',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
  },
  WHATSAPP_CATALOG: {
    id: 'WHATSAPP_CATALOG',
    category: 'marketing_assets',
    humanCategory: 'Social Media',
    label: 'WhatsApp Product Card',
    description: 'Clean visual tailored for fast WhatsApp sharing and customer chat inquiries.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['marketingText', 'brandContext'],
    promptTemplate: 'Clean WhatsApp business showcase of {SUBJECT}. High contrast, easily legible on small phone screens, pure focus on product authenticity with soft neutral frame.',
    preservationRules: ['Ensure product is immediately identifiable on mobile screens.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'marketing_graphic',
    languageSupport: true,
    badge: 'WhatsApp Ready',
  },
  FACEBOOK_POST: {
    id: 'FACEBOOK_POST',
    category: 'marketing_assets',
    humanCategory: 'Social Media',
    label: 'Facebook Marketing Post',
    description: 'Landscape or square marketing visual with clear product story and clean framing.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['marketingText', 'brandContext'],
    promptTemplate: 'Engaging Facebook marketing creative featuring {SUBJECT}. Clear product presentation with authentic cultural touch, designed for community shares and artisan story discovery.',
    preservationRules: ['Maintain product integrity for commercial trust.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
  },
  PRODUCT_PROMO_BANNER: {
    id: 'PRODUCT_PROMO_BANNER',
    category: 'marketing_assets',
    humanCategory: 'Marketing',
    label: 'Promotional Banner',
    description: 'Commercial promotional visual with controlled negative space for headlines.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['marketingText', 'brandContext'],
    promptTemplate: 'Commercial promotional banner featuring {SUBJECT} anchored on the right or left with clean open negative space on the opposite side for campaign messaging. Sophisticated color grading.',
    preservationRules: ['Reserve clean empty space for user text; do not hallucinate fake prices.'],
    aspectRatioRules: '16:9',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
  },
  FESTIVAL_PROMOTION: {
    id: 'FESTIVAL_PROMOTION',
    category: 'marketing_assets',
    humanCategory: 'Seasonal',
    label: 'Festival Campaign Creative',
    description: 'Festive commercial creative tailored for holiday sales and seasonal promotions.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['festivalOrOccasion', 'marketingText', 'brandContext'],
    promptTemplate: 'Festive campaign visual celebrating {OCCASION} with {SUBJECT} as the star gift. Elegant festive border or background accents, warm golden glow, celebratory Indian aesthetic.',
    preservationRules: ['No random or cheesy decorations; keep elegant and culturally respectful.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
    badge: 'Festive Special',
  },
  NEW_PRODUCT_LAUNCH: {
    id: 'NEW_PRODUCT_LAUNCH',
    category: 'marketing_assets',
    humanCategory: 'Marketing',
    label: 'New Arrival / Launch Card',
    description: 'Launch-themed visual celebrating a fresh design or new craft addition.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'New collection launch showcase for {SUBJECT}. Sculptural pedestal, dramatic subtle unveiling spotlight, editorial fashion/craft look announcing a fresh handcrafted creation.',
    preservationRules: ['Hero focus on the exact new craft item.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
  },
  SALE_PROMOTION: {
    id: 'SALE_PROMOTION',
    category: 'marketing_assets',
    humanCategory: 'Marketing',
    label: 'Special Offer Creative',
    description: 'Sale-oriented layout with clean space for user-provided discount or bundle info.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['marketingText', 'brandContext'],
    promptTemplate: 'Special offer promotional graphic featuring {SUBJECT}. Tasteful festive discount ambience, balanced negative space reserved for offer details, premium retail aesthetic.',
    preservationRules: ['Never invent fake discounts; only display user-approved text.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
  },
  GIFT_PROMOTION: {
    id: 'GIFT_PROMOTION',
    category: 'marketing_assets',
    humanCategory: 'Marketing',
    label: 'Gift Guide Showcase',
    description: 'Position product as a thoughtful handmade gift with artisanal charm.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['marketingText', 'brandContext'],
    promptTemplate: 'Curated gift guide presentation of {SUBJECT}. Placed on clean linen beside a tasteful handwritten-style artisan tag and botanical sprig. Inspires gifting handmade art.',
    preservationRules: ['Product remains completely visible and undamaged.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
  },
  B2B_PROMOTION: {
    id: 'B2B_PROMOTION',
    category: 'marketing_assets',
    humanCategory: 'Catalog',
    label: 'B2B / Wholesale Showcase',
    description: 'Professional wholesale/buyer-oriented visual emphasizing bulk craftsmanship & reliability.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['marketingText', 'brandContext'],
    promptTemplate: 'B2B wholesale catalog visual showcasing {SUBJECT}. Clean industrial or trade-fair styling, structured framing, highlighting craftsmanship consistency and production quality for retail buyers.',
    preservationRules: ['Convey professional reliability and authentic handmade consistency.'],
    aspectRatioRules: '16:9',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
    badge: 'Wholesale / B2B',
  },

  // ------------------------------------------------------------
  // CATEGORY E — BRANDING (46-54)
  // ------------------------------------------------------------
  BRAND_COLORS_APPLIED: {
    id: 'BRAND_COLORS_APPLIED',
    category: 'branding',
    humanCategory: 'Branding',
    label: 'Apply Brand Palette',
    description: 'Incorporate your enterprise brand colors harmoniously into the background environment.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Brand-harmonized product showcase of {SUBJECT}. The backdrop and ambient surface subtly incorporate the enterprise brand color palette ({BRAND_COLORS}) without changing the product itself.',
    preservationRules: ['Never recolor the product itself; apply brand colors exclusively to background framing.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'branding_asset',
    languageSupport: false,
    badge: 'Branded',
  },
  BRAND_BACKGROUND: {
    id: 'BRAND_BACKGROUND',
    category: 'branding',
    humanCategory: 'Branding',
    label: 'Branded Identity Backdrop',
    description: 'Create a distinctive studio background aligned with your artisan workshop identity.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Custom branded background environment for {SUBJECT} echoing the {BRAND_NAME} artisanal identity. Distinctive textured arch or soft geometric tone-on-tone paneling.',
    preservationRules: ['Keep product colors true and unaltered.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'branding_asset',
    languageSupport: false,
  },
  LOGO_PLACEMENT: {
    id: 'LOGO_PLACEMENT',
    category: 'branding',
    humanCategory: 'Branding',
    label: 'Tasteful Logo Watermark',
    description: 'Place your official logo tastefully in a corner or watermark safe zone.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Clean e-commerce product visual of {SUBJECT} with discrete, professional logo integration space in the top-right corner. Clean margin preservation.',
    preservationRules: ['Do not alter or redraw user logo; preserve original vector/image integrity.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'branding_asset',
    languageSupport: false,
  },
  BRAND_STYLED_PRODUCT: {
    id: 'BRAND_STYLED_PRODUCT',
    category: 'branding',
    humanCategory: 'Branding',
    label: 'Cohesive Brand Presentation',
    description: 'Full brand cohesion across lighting, backdrop, and accent styling for catalog uniformity.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Signature brand photograph for {BRAND_NAME} featuring {SUBJECT}. Consistent studio lighting, signature earthen tones, premium artisan positioning.',
    preservationRules: ['Ensure catalog-wide visual consistency across all products.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'branding_asset',
    languageSupport: false,
  },
  PACKAGING_MOCKUP: {
    id: 'PACKAGING_MOCKUP',
    category: 'branding',
    humanCategory: 'Branding',
    label: 'Eco-Packaging Concept',
    description: 'Show the product accompanied by an eco-friendly craft box or cotton drawstring pouch.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Sustainable packaging concept showcasing {SUBJECT} alongside a recycled brown cardboard box or organic unbleached cotton pouch featuring {BRAND_NAME} identity. Elegant unboxing feel.',
    preservationRules: ['Product remains primary hero beside or emerging from the package.'],
    aspectRatioRules: '1:1',
    modelPreference: 'professional',
    outputType: 'branding_asset',
    languageSupport: false,
  },
  THANK_YOU_CARD: {
    id: 'THANK_YOU_CARD',
    category: 'branding',
    humanCategory: 'Branding',
    label: 'Artisan Thank You Card',
    description: 'Create a heartfelt thank-you card concept highlighting your handmade story.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext', 'marketingText'],
    promptTemplate: 'Heartfelt artisan thank you card visual featuring a miniature artistic depiction of {SUBJECT} and elegant handwritten-style message thanking the buyer for supporting rural livelihoods.',
    preservationRules: ['Warm personal tone without commercial clutter.'],
    aspectRatioRules: '4:5',
    modelPreference: 'production',
    outputType: 'branding_asset',
    languageSupport: true,
  },
  PRODUCT_LABEL: {
    id: 'PRODUCT_LABEL',
    category: 'branding',
    humanCategory: 'Branding',
    label: 'Craft Tag / Label Mockup',
    description: 'Design an authentic Kraft paper craft tag concept attached with jute twine.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Detailed macro view of {SUBJECT} with an artisanal craft tag tied gently with natural twine. Tag displays {BRAND_NAME} and 100% Handcrafted stamp.',
    preservationRules: ['Product texture and craftsmanship remains in sharp focus.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'branding_asset',
    languageSupport: false,
  },
  QR_CARD: {
    id: 'QR_CARD',
    category: 'branding',
    humanCategory: 'Branding',
    label: 'Storefront QR Card Concept',
    description: 'Branded table card concept with placeholder for your WhatsApp / Storefront QR.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Clean counter display card featuring {SUBJECT} with an elegant reserved box for digital QR code to scan and explore artisan story on KRIVIO AI.',
    preservationRules: ['Ensure clean high-contrast area for scannable code.'],
    aspectRatioRules: '4:5',
    modelPreference: 'production',
    outputType: 'branding_asset',
    languageSupport: true,
  },
  BRAND_STORY_VISUAL: {
    id: 'BRAND_STORY_VISUAL',
    category: 'branding',
    humanCategory: 'Branding',
    label: 'Artisan Heritage Story Visual',
    description: 'Visual storytelling asset celebrating your craft technique, region, and tradition.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Evocative storytelling editorial image of {SUBJECT} paying homage to traditional {CRAFT_TYPE} from {REGION}. Rich cultural mood, dignified portrayal of living craft heritage.',
    preservationRules: ['Honor authentic regional artistic traditions without caricature.'],
    aspectRatioRules: '16:9',
    modelPreference: 'professional',
    outputType: 'branding_asset',
    languageSupport: true,
    badge: 'Brand Story',
  },

  // ------------------------------------------------------------
  // CATEGORY F — CATALOG / BUSINESS ASSETS (55-60)
  // ------------------------------------------------------------
  PRODUCT_CATALOG_COVER: {
    id: 'PRODUCT_CATALOG_COVER',
    category: 'catalog_assets',
    humanCategory: 'Catalog',
    label: 'Wholesale Catalog Cover',
    description: 'Create a stunning title cover page for your artisan enterprise product catalog.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Prestige catalog cover page featuring {SUBJECT} as the hero centerpiece. Minimalist modern Indian layout with {BRAND_NAME} title area, season identifier, and luxurious negative space.',
    preservationRules: ['Editorial cover layout with balanced typography margins.'],
    aspectRatioRules: '4:5',
    modelPreference: 'professional',
    outputType: 'catalog_page',
    languageSupport: true,
  },
  PRODUCT_CATALOG_PAGE: {
    id: 'PRODUCT_CATALOG_PAGE',
    category: 'catalog_assets',
    humanCategory: 'Catalog',
    label: 'Clean Catalog Spec Page',
    description: 'Clean product catalog page layout with clean photo area and spec card margins.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext', 'marketingText'],
    promptTemplate: 'Professional B2B catalog specification sheet highlighting {SUBJECT}. Crisp studio photo on white background alongside organized layout areas for product dimensions, materials, and artisan notes.',
    preservationRules: ['Clear division between image and text areas.'],
    aspectRatioRules: '4:5',
    modelPreference: 'production',
    outputType: 'catalog_page',
    languageSupport: true,
  },
  WHOLESALE_CATALOG: {
    id: 'WHOLESALE_CATALOG',
    category: 'catalog_assets',
    humanCategory: 'Catalog',
    label: 'Export / Wholesale Feature',
    description: 'B2B buyer sheet visual emphasizing consistency, packaging readiness, and export appeal.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Export-ready wholesale presentation card of {SUBJECT}. Sharp studio lighting, neutral grey backdrop, displaying high craftsmanship standards suitable for international buyers.',
    preservationRules: ['Flawless depiction of actual product quality.'],
    aspectRatioRules: '16:9',
    modelPreference: 'production',
    outputType: 'catalog_page',
    languageSupport: false,
  },
  QUOTATION_COVER: {
    id: 'QUOTATION_COVER',
    category: 'catalog_assets',
    humanCategory: 'Catalog',
    label: 'Business Quotation Header',
    description: 'Professional visual header for corporate gifting proposals and bulk price quotes.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Corporate proposal visual header featuring {SUBJECT}. Professional, trustworthy presentation with warm corporate artisan aesthetic.',
    preservationRules: ['Professional business tone.'],
    aspectRatioRules: '16:9',
    modelPreference: 'production',
    outputType: 'catalog_page',
    languageSupport: false,
  },
  PRODUCT_COLLECTION: {
    id: 'PRODUCT_COLLECTION',
    category: 'catalog_assets',
    humanCategory: 'Catalog',
    label: 'Collection Cohesion Shot',
    description: 'Create a harmonious group or collection styling around the hero piece.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Curated collection showcase highlighting {SUBJECT} in harmony with subtle complementary tones. Balanced visual rhythm, clean studio floor.',
    preservationRules: ['Hero product remains unmistakably distinct and sharp.'],
    aspectRatioRules: '16:9',
    modelPreference: 'production',
    outputType: 'catalog_page',
    languageSupport: false,
  },
  PRODUCT_COMPARISON: {
    id: 'PRODUCT_COMPARISON',
    category: 'catalog_assets',
    humanCategory: 'Catalog',
    label: 'Handmade vs Machine-made Guide',
    description: 'Visual highlighting the authentic hallmarks of genuine handcrafting over factory copies.',
    requiredInputs: ['originalImage'],
    optionalInputs: [],
    promptTemplate: 'Educational craft appreciation visual highlighting {SUBJECT} focusing on authentic handloom weave or hand-carving markers that prove genuine artisan origin.',
    preservationRules: ['Focus on celebrating real craftsmanship hallmarks.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'catalog_page',
    languageSupport: true,
  },

  // ------------------------------------------------------------
  // CATEGORY G — SEASONAL / CULTURAL (61-67)
  // ------------------------------------------------------------
  DIWALI: {
    id: 'DIWALI',
    category: 'seasonal_cultural',
    humanCategory: 'Seasonal',
    label: 'Diwali Festive Splendor',
    description: 'Celebrate the festival of lights with warm glowing terracotta diyas and golden aura.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext', 'marketingText'],
    promptTemplate: 'Elegant Diwali festival celebration image featuring {SUBJECT}. Traditional terracotta diyas with gentle warm flickering flames in the soft-focus background, delicate marigold garland curves, festive golden luminescence. The product is the central auspicious gift.',
    preservationRules: ['Diyas and flowers strictly frame the product from background; product itself remains 100% visible.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
    badge: 'Diwali',
  },
  HOLI: {
    id: 'HOLI',
    category: 'seasonal_cultural',
    humanCategory: 'Seasonal',
    label: 'Holi Colors Celebration',
    description: 'Celebrate the festival of colors with dry organic herbal gulal powders in background.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Vibrant yet tasteful Holi festival showcase of {SUBJECT}. Placed beside small wooden bowls of organic pink, turquoise and saffron dry gulal powder. Celebratory joyful mood, zero powder on product itself.',
    preservationRules: ['Product must stay clean and pristine; color powders remain in decorative bowls.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
    badge: 'Holi',
  },
  NAVRATRI: {
    id: 'NAVRATRI',
    category: 'seasonal_cultural',
    humanCategory: 'Seasonal',
    label: 'Navratri & Durga Puja Theme',
    description: 'Traditional celebration aesthetic with festive red, ochre and traditional motifs.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Navratri and Durga Puja festive showcase featuring {SUBJECT}. Traditional earthen tones, brass bell accents in bokeh, auspicious red and gold festive warmth.',
    preservationRules: ['Dignified devotional and festive aesthetics; product unaltered.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
    badge: 'Navratri',
  },
  EID: {
    id: 'EID',
    category: 'seasonal_cultural',
    humanCategory: 'Seasonal',
    label: 'Eid Festive Elegance',
    description: 'Refined celebration with crescent motifs, brass lanterns and midnight emerald tones.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Refined Eid festive presentation of {SUBJECT}. Deep royal emerald and warm gold ambient tones, tasteful brass filigree lantern in the soft background, peaceful elegant celebratory ambience.',
    preservationRules: ['Strictly tasteful, culturally accurate, product centered.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
    badge: 'Eid',
  },
  CHRISTMAS: {
    id: 'CHRISTMAS',
    category: 'seasonal_cultural',
    humanCategory: 'Seasonal',
    label: 'Winter & Holiday Season',
    description: 'Winter holiday gifting theme with warm fairy lights and pinecone accents.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Cozy winter holiday gifting showcase of {SUBJECT}. Warm fairy lights softly bokeh in background, rustic wooden table, evergreen pine branch resting naturally nearby.',
    preservationRules: ['Product remains untouched as the hero holiday gift.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
  },
  WEDDING_GIFTING: {
    id: 'WEDDING_GIFTING',
    category: 'seasonal_cultural',
    humanCategory: 'Seasonal',
    label: 'Royal Wedding Gifting',
    description: 'Opulent yet restrained Indian wedding gifting aesthetic with raw silk and rose petals.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Indian wedding trousseau and gifting presentation of {SUBJECT}. Resting on rich raw silk fabric, fresh scattered red rose petals, auspicious golden celebratory aesthetic.',
    preservationRules: ['Elevate heritage elegance while preserving original craft color.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
    badge: 'Wedding',
  },
  LOCAL_FESTIVAL: {
    id: 'LOCAL_FESTIVAL',
    category: 'seasonal_cultural',
    humanCategory: 'Seasonal',
    label: 'Regional Harvest & Fair',
    description: 'Celebrate regional festivals (Pongal, Onam, Bihu, Sankranti, Mela) with authentic touch.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['festivalOrOccasion', 'brandContext'],
    promptTemplate: 'Authentic harvest festival celebration of {OCCASION} featuring {SUBJECT}. Sunlit courtyard, sugarcane or earthen pot harvest accents softly blurred in background, joyful cultural pride.',
    preservationRules: ['Respect regional traditions authentically without generic stereotyping.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
  },

  // ------------------------------------------------------------
  // CATEGORY H — ADVANCED EDITING (68-78)
  // ------------------------------------------------------------
  OBJECT_REMOVE: {
    id: 'OBJECT_REMOVE',
    category: 'advanced_editing',
    humanCategory: 'Advanced Touch-Up',
    label: 'Remove Distracting Object',
    description: 'Cleanly remove a specific unwanted object or person from around the product.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['userInstruction'],
    promptTemplate: 'Flawless precision inpainting edit for {SUBJECT}. Remove {USER_INSTRUCTION} from the scene and seamlessly fill the vacated background with natural matching studio textures.',
    preservationRules: ['Product boundary and shadow must remain 100% untouched.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
    badge: 'Precision',
  },
  OBJECT_REPLACE: {
    id: 'OBJECT_REPLACE',
    category: 'advanced_editing',
    humanCategory: 'Advanced Touch-Up',
    label: 'Replace Background Element',
    description: 'Replace an awkward prop or background piece with a clean tasteful alternative.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['userInstruction'],
    promptTemplate: 'Selective element replacement around {SUBJECT}. Replace {USER_INSTRUCTION} with a tasteful neutral artisan styling accent.',
    preservationRules: ['The product itself must never be replaced or modified.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: false,
  },
  BACKGROUND_CHANGE: {
    id: 'BACKGROUND_CHANGE',
    category: 'advanced_editing',
    humanCategory: 'Advanced Touch-Up',
    label: 'Change Background to Custom Style',
    description: 'Completely transform the background environment according to your exact preference.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['userInstruction'],
    promptTemplate: 'Complete background transformation for {SUBJECT}. Isolate product perfectly and transpose onto {USER_INSTRUCTION}. Rebalance ambient lighting to match new environment naturally.',
    preservationRules: ['Product geometry, texture, and core lighting direction must stay locked.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: true,
  },
  SURFACE_CHANGE: {
    id: 'SURFACE_CHANGE',
    category: 'advanced_editing',
    humanCategory: 'Advanced Touch-Up',
    label: 'Change Table / Floor Surface',
    description: 'Swap only the supporting surface (e.g. marble, wood, jute, terracotta).',
    requiredInputs: ['originalImage'],
    optionalInputs: ['userInstruction'],
    promptTemplate: 'Surface replacement under {SUBJECT}. Place the product stably on {USER_INSTRUCTION} with realistic contact shadows and subtle surface reflections.',
    preservationRules: ['Product bottom contour must seat naturally without clipping.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: true,
  },
  PROP_ADD: {
    id: 'PROP_ADD',
    category: 'advanced_editing',
    humanCategory: 'Advanced Touch-Up',
    label: 'Add Subtle Prop',
    description: 'Add a tasteful supporting prop (e.g. fresh flower, clay bowl, botanical leaf).',
    requiredInputs: ['originalImage'],
    optionalInputs: ['userInstruction'],
    promptTemplate: 'Add a subtle contextual prop ({USER_INSTRUCTION}) beside {SUBJECT}. Prop must be secondary in size and slightly defocused, leaving the product as the hero.',
    preservationRules: ['Never obscure product with the new prop.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: true,
  },
  PROP_REMOVE: {
    id: 'PROP_REMOVE',
    category: 'advanced_editing',
    humanCategory: 'Advanced Touch-Up',
    label: 'Remove Unwanted Prop',
    description: 'Remove a cluttered or distracting prop already present in your photo.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['userInstruction'],
    promptTemplate: 'Clean removal of unwanted prop ({USER_INSTRUCTION}) around {SUBJECT}, restoring clean background continuity.',
    preservationRules: ['Zero collateral damage to product edges.'],
    aspectRatioRules: '1:1',
    modelPreference: 'fast',
    outputType: 'photo',
    languageSupport: false,
  },
  COMPOSITION_REFRAME: {
    id: 'COMPOSITION_REFRAME',
    category: 'advanced_editing',
    humanCategory: 'Advanced Touch-Up',
    label: 'Reframe & Reposition',
    description: 'Reframe the shot to achieve a new camera distance, angle, or position.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['userInstruction'],
    promptTemplate: 'Reframe composition for {SUBJECT}. Adjust perspective to {USER_INSTRUCTION} while maintaining absolute fidelity to the product appearance.',
    preservationRules: ['Preserve true product proportion from the new framing.'],
    aspectRatioRules: '1:1',
    modelPreference: 'production',
    outputType: 'photo',
    languageSupport: true,
  },
  MULTI_IMAGE_COMPOSITE: {
    id: 'MULTI_IMAGE_COMPOSITE',
    category: 'advanced_editing',
    humanCategory: 'Advanced Touch-Up',
    label: 'Multi-Reference Composition',
    description: 'Combine product with your logo and packaging references into one polished scene.',
    requiredInputs: ['originalImage', 'referenceImages'],
    optionalInputs: ['brandContext'],
    promptTemplate: 'Harmonious multi-asset composite bringing together primary {SUBJECT} with reference logo and packaging in a unified commercial studio setup.',
    preservationRules: ['Respect each reference asset roles without cross-contamination.'],
    aspectRatioRules: '1:1',
    modelPreference: 'professional',
    outputType: 'branding_asset',
    languageSupport: false,
  },
  BRAND_REFERENCE_STYLE: {
    id: 'BRAND_REFERENCE_STYLE',
    category: 'advanced_editing',
    humanCategory: 'Branding',
    label: 'Match Brand Style Reference',
    description: 'Adopt the lighting, color grading and mood of an approved reference image.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['referenceImages', 'brandContext'],
    promptTemplate: 'Style transfer and lighting adaptation for {SUBJECT}. Match the color grading, mood and studio ambiance of the reference brand style while preserving the exact product.',
    preservationRules: ['Apply only lighting and grading style; product shape is strictly locked.'],
    aspectRatioRules: '1:1',
    modelPreference: 'professional',
    outputType: 'photo',
    languageSupport: false,
  },
  PRODUCT_REFERENCE_LOCK: {
    id: 'PRODUCT_REFERENCE_LOCK',
    category: 'advanced_editing',
    humanCategory: 'Product Photo',
    label: 'Lock Product Identity',
    description: 'Enforce strict 100% identity lock on your original product photo across edits.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['userInstruction'],
    promptTemplate: 'Strict identity-locked commercial rendering of {SUBJECT}. Maximum preservation priority for colors, motifs, weave patterns and craftsmanship details. Edit environment as: {USER_INSTRUCTION}.',
    preservationRules: ['Absolute zero modification of the product itself. Only environment is eligible for modification.'],
    aspectRatioRules: '1:1',
    modelPreference: 'professional',
    outputType: 'photo',
    languageSupport: true,
    badge: 'Identity Lock',
  },
  CAMPAIGN_VARIANT: {
    id: 'CAMPAIGN_VARIANT',
    category: 'advanced_editing',
    humanCategory: 'Marketing',
    label: 'Generate Campaign Variation',
    description: 'Create a visually related variation for multi-channel marketing campaigns.',
    requiredInputs: ['originalImage'],
    optionalInputs: ['userInstruction', 'brandContext'],
    promptTemplate: 'Campaign variant for {SUBJECT}. Complementary composition maintaining core brand identity and lighting language while offering fresh visual variety for marketing ads.',
    preservationRules: ['Maintain clear visual brand continuity with previous assets.'],
    aspectRatioRules: '4:5',
    modelPreference: 'production',
    outputType: 'marketing_graphic',
    languageSupport: true,
  },
};

export const OPERATION_CATEGORIES = [
  {
    id: 'photo_cleanup',
    title: 'Product Photo Cleanup',
    description: 'Clean backgrounds, remove domestic clutter, fix shadows and get studio quality.',
    badge: 'Core',
  },
  {
    id: 'image_quality',
    title: 'Quality & Exposure',
    description: 'True-to-life colors, sharpness, balanced lighting and marketplace compliance.',
    badge: 'Enhance',
  },
  {
    id: 'lifestyle_context',
    title: 'Lifestyle & Real Context',
    description: 'Living rooms, dining tables, outdoor sun and artisanal workshop heritage.',
    badge: 'Believable',
  },
  {
    id: 'marketing_assets',
    title: 'Marketing & Social Media',
    description: 'Instagram feed & story, WhatsApp catalog, festive promos and wholesale banners.',
    badge: 'Growth',
  },
  {
    id: 'branding',
    title: 'Branding & Enterprise Identity',
    description: 'Apply your brand palette, logo placement, packaging mockups and thank you cards.',
    badge: 'Identity',
  },
  {
    id: 'catalog_assets',
    title: 'Catalog & Business Sheets',
    description: 'Wholesale catalog covers, spec sheets, B2B quotation headers and collection layouts.',
    badge: 'B2B',
  },
  {
    id: 'seasonal_cultural',
    title: 'Festive & Cultural Occasions',
    description: 'Diwali, Holi, Navratri, Eid, Christmas, Weddings and local Indian fairs.',
    badge: 'Festive',
  },
  {
    id: 'advanced_editing',
    title: 'Advanced Touch-Up',
    description: 'Custom background changes, object removal, prop adjustment and identity locking.',
    badge: 'Custom',
  },
];
